services:
  postgres:
    container_name: postgres
    image: docker.io/library/postgres:13.16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: docker.io/dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: pass
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 8888:80
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: ./backend
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/test
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
    ports:
      - 8080:8080
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - 80:80
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
